# Generated by Django 5.2 on 2025-05-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_participante_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
